development:
  password: xxx
  theme_id: xxx
  store: xxx.myshopify.com
# Windows	%APPDATA%\Shopify\Themekit\variables
# Linux/BSDs	${XDG_CONFIG_HOME}/Shopify/Themekit/variables
# MacOSX	${HOME}/Library/Application Support/Shopify/Themekit/variables
# Any	--vars flag provides a path to a file for loading variables
# file to load ignore patterns, check out the ignore file example
